// ---------------------------------------------------------------
// Static data: muscle groups + exercise database (no APIs, no AI)
// ---------------------------------------------------------------

const MUSCLES = {
  chest:      { name: 'Chest',      desc: 'Pectorals. Push things away from your body — pressing, hugging and throwing motions.' },
  shoulders:  { name: 'Shoulders',  desc: 'Deltoids. Lift your arms in every direction; they shape the top of your frame and assist every press.' },
  biceps:     { name: 'Biceps',     desc: 'Front of the upper arm. Bend the elbow and rotate the forearm — all pulling and curling.' },
  triceps:    { name: 'Triceps',    desc: 'Back of the upper arm (2/3 of its size). Straighten the elbow — every press finishes with triceps.' },
  forearms:   { name: 'Forearms',   desc: 'Grip and wrist strength. A stronger grip carries over to every pull, carry and deadlift.' },
  abs:        { name: 'Abs',        desc: 'Rectus abdominis. Flex the spine and brace your torso — your pressure belt for heavy lifts.' },
  obliques:   { name: 'Obliques',   desc: 'Sides of your waist. Rotate and side-bend the torso, resist twisting under load.' },
  traps:      { name: 'Traps',      desc: 'Upper back / neck. Shrug, hold and stabilise the shoulder blades; built by rows, shrugs and carries.' },
  lats:       { name: 'Lats',       desc: 'The big "wings" of your back. Pull things down and toward you — the width muscle.' },
  lowerback:  { name: 'Lower Back', desc: 'Spinal erectors. Keep your spine upright and safe; the foundation of deadlifts and posture.' },
  glutes:     { name: 'Glutes',     desc: 'Your biggest muscle. Hip drive — sprinting, jumping, standing up with weight.', leg: true },
  quads:      { name: 'Quads',      desc: 'Front of the thigh. Straighten the knee — squats, lunges, stairs, kicking.', leg: true },
  hamstrings: { name: 'Hamstrings', desc: 'Back of the thigh. Bend the knee and extend the hip — speed and deadlift strength.', leg: true },
  calves:     { name: 'Calves',     desc: 'Lower leg. Point the foot — every step, jump and sprint goes through them.', leg: true },
};

// Named splits used by the planner and the suggestion engine
const SPLITS = {
  push:       { name: 'Push Day',         short: 'Push',          muscles: ['chest', 'shoulders', 'triceps'] },
  pull:       { name: 'Pull Day',         short: 'Pull',          muscles: ['lats', 'traps', 'biceps', 'forearms'] },
  chesttri:   { name: 'Chest + Triceps',  short: 'Chest+Tri',     muscles: ['chest', 'triceps'] },
  backbi:     { name: 'Back + Biceps',    short: 'Back+Bi',       muscles: ['lats', 'traps', 'lowerback', 'biceps'] },
  shoulderday:{ name: 'Shoulder Day',     short: 'Shoulders',     muscles: ['shoulders', 'traps'] },
  arms:       { name: 'Arm Day',          short: 'Arms',          muscles: ['biceps', 'triceps', 'forearms'] },
  legs:       { name: 'Leg Day',          short: 'Legs',          muscles: ['quads', 'hamstrings', 'glutes', 'calves'] },
  upper:      { name: 'Upper Body',       short: 'Upper',         muscles: ['chest', 'shoulders', 'lats', 'traps', 'biceps', 'triceps'] },
  core:       { name: 'Core Day',         short: 'Core',          muscles: ['abs', 'obliques', 'lowerback'] },
  full:       { name: 'Full Body',        short: 'Full',          muscles: ['chest', 'lats', 'shoulders', 'quads', 'hamstrings', 'abs'] },
};

// equipment: barbell | dumbbell | machine | cable | bodyweight
// compound: true = multi-joint, gets picked first by the planner
const EXERCISES = [
  // --- Chest ---
  { id: 'bench-press',        name: 'Bench Press',            primary: ['chest'], secondary: ['triceps', 'shoulders'], equipment: 'barbell',    compound: true,
    desc: 'Lie on a bench, lower the bar to your chest and press it up. The classic chest mass and strength builder.' },
  { id: 'incline-bench',      name: 'Incline Bench Press',    primary: ['chest', 'shoulders'], secondary: ['triceps'], equipment: 'barbell',    compound: true,
    desc: 'Bench press on a 30–45° incline. Shifts the work to the upper chest and front delts.' },
  { id: 'db-bench-press',     name: 'Dumbbell Bench Press',   primary: ['chest'], secondary: ['triceps', 'shoulders'], equipment: 'dumbbell',   compound: true,
    desc: 'Bench press with dumbbells. Bigger range of motion than the bar and each side works independently.' },
  { id: 'incline-db-press',   name: 'Incline Dumbbell Press', primary: ['chest'], secondary: ['shoulders', 'triceps'], equipment: 'dumbbell',   compound: true,
    desc: 'Dumbbell press on an incline bench — targets the upper chest, the part most people lack.' },
  { id: 'pushup',             name: 'Push-Up',                primary: ['chest'], secondary: ['triceps', 'shoulders', 'abs'], equipment: 'bodyweight', compound: true,
    desc: 'The fundamental bodyweight press. Keep a straight line from head to heels; chest to the floor each rep.' },
  { id: 'decline-pushup',     name: 'Decline Push-Up',        primary: ['chest', 'shoulders'], secondary: ['triceps'], equipment: 'bodyweight', compound: true,
    desc: 'Push-up with your feet elevated on a bench or chair. Harder than normal and hits the upper chest more.' },
  { id: 'chest-fly',          name: 'Dumbbell Chest Fly',     primary: ['chest'], secondary: [],                       equipment: 'dumbbell',   compound: false,
    desc: 'Lying down, open your arms wide and squeeze them together over your chest. Pure chest isolation and stretch.' },
  { id: 'cable-crossover',    name: 'Cable Crossover',        primary: ['chest'], secondary: [],                       equipment: 'cable',      compound: false,
    desc: 'Pull two high cables down and across your body. Constant tension on the chest through the whole motion.' },
  { id: 'pec-deck',           name: 'Pec Deck Machine',       primary: ['chest'], secondary: [],                       equipment: 'machine',    compound: false,
    desc: 'Seated fly machine. Easy to learn, locks you into the movement and isolates the chest safely.' },
  { id: 'chest-press-machine',name: 'Chest Press Machine',    primary: ['chest'], secondary: ['triceps'],              equipment: 'machine',    compound: true,
    desc: 'Machine version of the bench press. Great for pushing close to failure without a spotter.' },
  { id: 'dips',               name: 'Dips',                   primary: ['chest', 'triceps'], secondary: ['shoulders'], equipment: 'bodyweight', compound: true,
    desc: 'Support yourself on parallel bars and lower until elbows hit 90°. Lean forward for chest, stay upright for triceps.' },

  // --- Back ---
  { id: 'pullup',             name: 'Pull-Up',                primary: ['lats'], secondary: ['biceps', 'forearms'],    equipment: 'bodyweight', compound: true,
    desc: 'Hang from a bar with palms facing away and pull your chin over it. The king of back-width exercises.' },
  { id: 'chinup',             name: 'Chin-Up',                primary: ['lats', 'biceps'], secondary: ['forearms'],    equipment: 'bodyweight', compound: true,
    desc: 'Pull-up with palms facing you. Easier than a pull-up and brings the biceps in heavily.' },
  { id: 'lat-pulldown',       name: 'Lat Pulldown',           primary: ['lats'], secondary: ['biceps'],                equipment: 'cable',      compound: true,
    desc: 'Pull a wide bar down to your collarbone. The machine version of a pull-up — scale the weight to you.' },
  { id: 'barbell-row',        name: 'Barbell Row',            primary: ['lats', 'traps'], secondary: ['biceps', 'lowerback'], equipment: 'barbell', compound: true,
    desc: 'Hinge forward and row the bar to your stomach. Builds back thickness and a strong posture.' },
  { id: 'db-row',             name: 'One-Arm Dumbbell Row',   primary: ['lats'], secondary: ['biceps', 'traps'],       equipment: 'dumbbell',   compound: true,
    desc: 'One knee on a bench, row a dumbbell to your hip. Lets you focus on each side and protect the lower back.' },
  { id: 'seated-cable-row',   name: 'Seated Cable Row',       primary: ['lats', 'traps'], secondary: ['biceps'],       equipment: 'cable',      compound: true,
    desc: 'Sit and pull the handle to your stomach, squeezing the shoulder blades together. Smooth, constant tension.' },
  { id: 'tbar-row',           name: 'T-Bar Row',              primary: ['lats', 'traps'], secondary: ['biceps', 'lowerback'], equipment: 'barbell', compound: true,
    desc: 'Row a landmine/T-bar between your legs. Lets you load heavy with a stronger torso angle than barbell rows.' },
  { id: 'deadlift',           name: 'Deadlift',               primary: ['lowerback', 'hamstrings', 'glutes'], secondary: ['traps', 'lats', 'forearms'], equipment: 'barbell', compound: true,
    desc: 'Lift a loaded bar off the floor to standing. Trains the entire back side of your body at once.' },
  { id: 'back-extension',     name: 'Back Extension',         primary: ['lowerback'], secondary: ['glutes', 'hamstrings'], equipment: 'bodyweight', compound: false,
    desc: 'Hinge over a bench or roman chair and raise your torso. Strengthens the lower back safely with high reps.' },
  { id: 'superman',           name: 'Superman Hold',          primary: ['lowerback'], secondary: ['glutes'],           equipment: 'bodyweight', compound: false,
    desc: 'Lie face-down and lift arms and legs off the floor. Zero-equipment lower-back and posture work.' },
  { id: 'shrugs',             name: 'Dumbbell Shrugs',        primary: ['traps'], secondary: ['forearms'],             equipment: 'dumbbell',   compound: false,
    desc: 'Hold heavy dumbbells and shrug your shoulders straight up. Direct trap builder.' },
  { id: 'face-pull',          name: 'Face Pull',              primary: ['traps', 'shoulders'], secondary: [],          equipment: 'cable',      compound: false,
    desc: 'Pull a rope attachment toward your face with elbows high. The best exercise for healthy, balanced shoulders.' },
  { id: 'upright-row',        name: 'Upright Row',            primary: ['traps', 'shoulders'], secondary: ['biceps'],  equipment: 'barbell',    compound: true,
    desc: 'Pull the bar straight up your body to chest height, elbows leading. Hits traps and side delts together.' },

  // --- Shoulders ---
  { id: 'overhead-press',     name: 'Overhead Press',         primary: ['shoulders'], secondary: ['triceps', 'traps'], equipment: 'barbell',    compound: true,
    desc: 'Press a barbell from your shoulders to overhead while standing. The best test of upper-body pressing strength.' },
  { id: 'db-shoulder-press',  name: 'Dumbbell Shoulder Press',primary: ['shoulders'], secondary: ['triceps'],          equipment: 'dumbbell',   compound: true,
    desc: 'Press dumbbells overhead from shoulder height. More natural arm path than the barbell version.' },
  { id: 'arnold-press',       name: 'Arnold Press',           primary: ['shoulders'], secondary: ['triceps'],          equipment: 'dumbbell',   compound: true,
    desc: 'Shoulder press that starts palms-facing-you and rotates as you press. Hits all three heads of the delt.' },
  { id: 'lateral-raise',      name: 'Lateral Raise',          primary: ['shoulders'], secondary: [],                   equipment: 'dumbbell',   compound: false,
    desc: 'Raise light dumbbells out to your sides to shoulder height. Builds the side delts — the "wide shoulders" muscle.' },
  { id: 'cable-lateral',      name: 'Cable Lateral Raise',    primary: ['shoulders'], secondary: [],                   equipment: 'cable',      compound: false,
    desc: 'Lateral raise on a low cable. Keeps tension on the delt even at the bottom, unlike dumbbells.' },
  { id: 'front-raise',        name: 'Front Raise',            primary: ['shoulders'], secondary: [],                   equipment: 'dumbbell',   compound: false,
    desc: 'Raise dumbbells straight in front of you to shoulder height. Isolates the front delts.' },
  { id: 'rear-delt-fly',      name: 'Rear Delt Fly',          primary: ['shoulders'], secondary: ['traps'],            equipment: 'dumbbell',   compound: false,
    desc: 'Hinge forward and raise dumbbells out to the sides. Trains the rear delts most people forget.' },
  { id: 'reverse-pec-deck',   name: 'Reverse Pec Deck',       primary: ['shoulders'], secondary: ['traps'],            equipment: 'machine',    compound: false,
    desc: 'Sit facing the pec deck and open your arms backward. Easy, strict rear-delt isolation.' },
  { id: 'pike-pushup',        name: 'Pike Push-Up',           primary: ['shoulders'], secondary: ['triceps'],          equipment: 'bodyweight', compound: true,
    desc: 'Push-up in a downward-dog position, head toward the floor. Bodyweight shoulder pressing.' },

  // --- Arms ---
  { id: 'barbell-curl',       name: 'Barbell Curl',           primary: ['biceps'], secondary: ['forearms'],            equipment: 'barbell',    compound: false,
    desc: 'Curl a barbell from your thighs to your chest with strict form. The heaviest way to load the biceps.' },
  { id: 'db-curl',            name: 'Dumbbell Curl',          primary: ['biceps'], secondary: ['forearms'],            equipment: 'dumbbell',   compound: false,
    desc: 'Classic alternating or simultaneous curls. Rotate your palm up as you lift for a full biceps squeeze.' },
  { id: 'hammer-curl',        name: 'Hammer Curl',            primary: ['biceps', 'forearms'], secondary: [],          equipment: 'dumbbell',   compound: false,
    desc: 'Curl with palms facing each other. Builds the brachialis and forearms for thicker-looking arms.' },
  { id: 'incline-curl',       name: 'Incline Dumbbell Curl',  primary: ['biceps'], secondary: [],                      equipment: 'dumbbell',   compound: false,
    desc: 'Curl while lying back on an incline bench. Puts the biceps under a deep stretch — brutal and effective.' },
  { id: 'preacher-curl',      name: 'Preacher Curl',          primary: ['biceps'], secondary: [],                      equipment: 'machine',    compound: false,
    desc: 'Curl with your arms braced on a pad. Removes all cheating and momentum.' },
  { id: 'cable-curl',         name: 'Cable Curl',             primary: ['biceps'], secondary: ['forearms'],            equipment: 'cable',      compound: false,
    desc: 'Curl on a low cable. Constant tension through the whole rep, great as a finisher.' },
  { id: 'concentration-curl', name: 'Concentration Curl',     primary: ['biceps'], secondary: [],                      equipment: 'dumbbell',   compound: false,
    desc: 'Seated, elbow braced on your inner thigh, curl one arm at a time. Maximum isolation and peak contraction.' },
  { id: 'tricep-pushdown',    name: 'Tricep Pushdown',        primary: ['triceps'], secondary: [],                     equipment: 'cable',      compound: false,
    desc: 'Push a cable bar or rope down until your arms are straight, elbows pinned. The staple triceps isolation.' },
  { id: 'skullcrusher',       name: 'Skullcrusher',           primary: ['triceps'], secondary: [],                     equipment: 'barbell',    compound: false,
    desc: 'Lying down, lower the bar to your forehead and extend back up. Loads the triceps in a deep stretch.' },
  { id: 'overhead-extension', name: 'Overhead Tricep Extension', primary: ['triceps'], secondary: [],                  equipment: 'dumbbell',   compound: false,
    desc: 'Hold one dumbbell overhead with both hands and lower it behind your head. Stretches the long head of the triceps.' },
  { id: 'close-grip-bench',   name: 'Close-Grip Bench Press', primary: ['triceps'], secondary: ['chest', 'shoulders'], equipment: 'barbell',    compound: true,
    desc: 'Bench press with hands shoulder-width. Shifts the load from chest to triceps — the heavy triceps builder.' },
  { id: 'bench-dips',         name: 'Bench Dips',             primary: ['triceps'], secondary: ['chest'],              equipment: 'bodyweight', compound: false,
    desc: 'Hands on a bench behind you, lower your hips and press back up. Triceps anywhere there is a chair.' },
  { id: 'diamond-pushup',     name: 'Diamond Push-Up',        primary: ['triceps'], secondary: ['chest'],              equipment: 'bodyweight', compound: true,
    desc: 'Push-up with hands together in a diamond shape. The hardest push-up variation for triceps.' },
  { id: 'wrist-curl',         name: 'Wrist Curl',             primary: ['forearms'], secondary: [],                    equipment: 'dumbbell',   compound: false,
    desc: 'Forearms on your thighs, curl the weight using only your wrists. Direct forearm size work.' },
  { id: 'reverse-curl',       name: 'Reverse Curl',           primary: ['forearms', 'biceps'], secondary: [],          equipment: 'barbell',    compound: false,
    desc: 'Curl with palms facing down. Hammers the forearm extensors and brachialis.' },
  { id: 'farmers-carry',      name: "Farmer's Carry",         primary: ['forearms', 'traps'], secondary: ['abs'],      equipment: 'dumbbell',   compound: true,
    desc: 'Pick up heavy dumbbells and walk. Grip, traps, core and posture — strongman simplicity.' },
  { id: 'dead-hang',          name: 'Dead Hang',              primary: ['forearms'], secondary: ['lats'],              equipment: 'bodyweight', compound: false,
    desc: 'Hang from a bar as long as you can. Builds grip endurance and decompresses the spine.' },

  // --- Core ---
  { id: 'plank',              name: 'Plank',                  primary: ['abs'], secondary: ['obliques', 'lowerback'],  equipment: 'bodyweight', compound: false,
    desc: 'Hold a straight line on your forearms and toes. Anti-collapse core strength — quality over time held.' },
  { id: 'crunch',             name: 'Crunch',                 primary: ['abs'], secondary: [],                         equipment: 'bodyweight', compound: false,
    desc: 'Curl your shoulders off the floor toward your hips. Simple, direct ab flexion.' },
  { id: 'bicycle-crunch',     name: 'Bicycle Crunch',         primary: ['abs', 'obliques'], secondary: [],             equipment: 'bodyweight', compound: false,
    desc: 'Alternate elbow to opposite knee in a pedaling motion. Hits abs and obliques together.' },
  { id: 'leg-raise',          name: 'Hanging Leg Raise',      primary: ['abs'], secondary: ['obliques', 'forearms'],   equipment: 'bodyweight', compound: false,
    desc: 'Hang from a bar and raise your legs to horizontal or higher. The hardest and best lower-ab exercise.' },
  { id: 'lying-leg-raise',    name: 'Lying Leg Raise',        primary: ['abs'], secondary: [],                         equipment: 'bodyweight', compound: false,
    desc: 'Lie flat and raise straight legs to vertical, lower slowly without touching down. Lower-ab focus, no bar needed.' },
  { id: 'russian-twist',      name: 'Russian Twist',          primary: ['obliques'], secondary: ['abs'],               equipment: 'bodyweight', compound: false,
    desc: 'Seated, lean back and rotate your torso side to side. Add weight to progress.' },
  { id: 'side-plank',         name: 'Side Plank',             primary: ['obliques'], secondary: ['abs'],               equipment: 'bodyweight', compound: false,
    desc: 'Plank on one forearm, body sideways. Builds the obliques and protects the lower back.' },
  { id: 'cable-woodchop',     name: 'Cable Woodchop',         primary: ['obliques'], secondary: ['abs'],               equipment: 'cable',      compound: false,
    desc: 'Pull a cable diagonally across your body like chopping wood. Rotational power for the waist.' },
  { id: 'ab-wheel',           name: 'Ab Wheel Rollout',       primary: ['abs'], secondary: ['lats', 'lowerback'],      equipment: 'bodyweight', compound: false,
    desc: 'Roll the wheel out as far as you can control and pull back. Elite-level core strength builder.' },
  { id: 'mountain-climber',   name: 'Mountain Climbers',      primary: ['abs'], secondary: ['obliques', 'quads'],      equipment: 'bodyweight', compound: false,
    desc: 'In a push-up position, drive your knees to your chest alternately, fast. Core plus conditioning.' },
  { id: 'dead-bug',           name: 'Dead Bug',               primary: ['abs'], secondary: ['obliques'],               equipment: 'bodyweight', compound: false,
    desc: 'On your back, extend opposite arm and leg while keeping your lower back glued down. Core control, zero strain.' },

  // --- Legs ---
  { id: 'squat',              name: 'Barbell Squat',          primary: ['quads', 'glutes'], secondary: ['hamstrings', 'lowerback', 'abs'], equipment: 'barbell', compound: true,
    desc: 'Bar on your back, sit down until thighs hit parallel, stand up. The king of leg exercises.' },
  { id: 'front-squat',        name: 'Front Squat',            primary: ['quads'], secondary: ['glutes', 'abs'],        equipment: 'barbell',    compound: true,
    desc: 'Squat with the bar racked on your front shoulders. More quads, more core, more upright posture.' },
  { id: 'goblet-squat',       name: 'Goblet Squat',           primary: ['quads', 'glutes'], secondary: ['abs'],        equipment: 'dumbbell',   compound: true,
    desc: 'Hold one dumbbell at your chest and squat. The best way to learn perfect squat form.' },
  { id: 'bodyweight-squat',   name: 'Bodyweight Squat',       primary: ['quads', 'glutes'], secondary: [],             equipment: 'bodyweight', compound: true,
    desc: 'The unloaded squat. High reps anywhere — hotel rooms, home, warm-ups.' },
  { id: 'leg-press',          name: 'Leg Press',              primary: ['quads', 'glutes'], secondary: ['hamstrings'], equipment: 'machine',    compound: true,
    desc: 'Press the sled away with your feet. Heavy leg work without loading your spine.' },
  { id: 'lunge',              name: 'Walking Lunge',          primary: ['quads', 'glutes'], secondary: ['hamstrings', 'calves'], equipment: 'dumbbell', compound: true,
    desc: 'Step forward into a deep lunge, alternate legs as you walk. Strength, balance and a serious burn.' },
  { id: 'bulgarian-split',    name: 'Bulgarian Split Squat',  primary: ['quads', 'glutes'], secondary: ['hamstrings'], equipment: 'dumbbell',   compound: true,
    desc: 'Rear foot elevated on a bench, squat on the front leg. The most effective (and most hated) single-leg builder.' },
  { id: 'step-up',            name: 'Dumbbell Step-Up',       primary: ['quads', 'glutes'], secondary: ['calves'],     equipment: 'dumbbell',   compound: true,
    desc: 'Step onto a box or bench holding dumbbells, drive through the top leg. Functional single-leg power.' },
  { id: 'leg-extension',      name: 'Leg Extension',          primary: ['quads'], secondary: [],                       equipment: 'machine',    compound: false,
    desc: 'Extend your knees against the pad. Pure quad isolation and a great pump finisher.' },
  { id: 'romanian-deadlift',  name: 'Romanian Deadlift',      primary: ['hamstrings', 'glutes'], secondary: ['lowerback', 'forearms'], equipment: 'barbell', compound: true,
    desc: 'Lower the bar down your legs with a flat back until your hamstrings scream, then stand. The hamstring builder.' },
  { id: 'db-rdl',             name: 'Dumbbell RDL',           primary: ['hamstrings', 'glutes'], secondary: ['lowerback'], equipment: 'dumbbell', compound: true,
    desc: 'Romanian deadlift with dumbbells. Same hamstring stretch, easier to learn and do at home.' },
  { id: 'leg-curl',           name: 'Leg Curl',               primary: ['hamstrings'], secondary: [],                  equipment: 'machine',    compound: false,
    desc: 'Curl your heels toward your glutes against the pad. Direct hamstring isolation.' },
  { id: 'nordic-curl',        name: 'Nordic Curl',            primary: ['hamstrings'], secondary: [],                  equipment: 'bodyweight', compound: false,
    desc: 'Anchor your heels and lower your body forward under control. Brutal bodyweight hamstring strength.' },
  { id: 'hip-thrust',         name: 'Hip Thrust',             primary: ['glutes'], secondary: ['hamstrings'],          equipment: 'barbell',    compound: true,
    desc: 'Upper back on a bench, bar over your hips, drive up and squeeze. The most direct glute builder there is.' },
  { id: 'glute-bridge',       name: 'Glute Bridge',           primary: ['glutes'], secondary: ['hamstrings', 'abs'],   equipment: 'bodyweight', compound: false,
    desc: 'Lie on your back and drive your hips to the ceiling. The no-equipment hip thrust.' },
  { id: 'calf-raise',         name: 'Standing Calf Raise',    primary: ['calves'], secondary: [],                      equipment: 'bodyweight', compound: false,
    desc: 'Rise onto your toes, pause, lower slowly. Do them on a step for a full stretch; load with dumbbells to progress.' },
  { id: 'seated-calf-raise',  name: 'Seated Calf Raise',      primary: ['calves'], secondary: [],                      equipment: 'machine',    compound: false,
    desc: 'Calf raises with bent knees. Targets the soleus, the deep calf muscle standing raises miss.' },
];

const EXERCISES_BY_ID = Object.fromEntries(EXERCISES.map(e => [e.id, e]));
